## Sample github actions workflow which prints environment name and has one job per environment dev , qa, uat,preprod,prod

name: Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  quality_checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: list directories
        run: |
          ls -latr
          pwd
          tree
      - name: Print Environment
        run: echo "Running quality checks"
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment
        run: echo "Running tests"

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [quality_checks, tests]
    steps:
      - name: Print Environment
        run: echo "Running build"
  dev:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    environment: dev
    needs: [build]
    steps:
      - name: Print Environment
        run: echo "Deploying to dev"

  qaauto:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    environment: qaauto
    needs: [dev]
    steps:
      - name: Print Environment
        run: echo "Deploying to qaauto"

  qa:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    environment: qa
    needs: [qaauto]
    steps:
      - name: Print Environment
        run: echo "Deploying to qa"

  uat:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    environment: uat
    needs: [qa]
    steps:
      - name: Print Environment
        run: echo "Deploying to uat"

  preprod:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [uat]
    environment: preprod
    steps:
      - name: Print Environment
        run: echo "Deploying to preprod"

  prod:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [preprod]
    environment: prod
    steps:
      - name: Print Environment
        run: echo "Deploying to prod"
