## Sample github actions workflow which prints environment name and has one job per environment dev , qa, uat,preprod,prod

name: Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - hotfix-uat/**
      - hotfix-prod/**

concurrency: 
  cancel-in-progress: false
  group: ${{ github.ref_name }}

jobs:
  quality_checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: list directories
        run: |
          ls -latr
          pwd
          tree
      - name: Print Environment
        run: echo "Running quality checks"
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment
        run: echo "Running tests"

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [quality_checks, tests]
    steps:
      - name: Print Environment
        run: echo "Running build"
  dev:
    runs-on: ubuntu-latest
    if:  github.ref_name == 'main'
    environment: dev
    needs: [build]
    steps:
      - name: Print Environment
        run: echo "Deploying to dev"

  qaauto:
    runs-on: ubuntu-latest
    if:  github.ref_name == 'main'
    environment: qaauto
    needs: [dev]
    steps:
      - name: Print Environment
        run: |
          echo "Deploying to qaauto"
          sleep 120

  qa:
    runs-on: ubuntu-latest
    if:  github.ref_name == 'main'
    environment: qa
    needs: [qaauto]
    steps:
      - name: Print Environment
        run: echo "Deploying to qa"

  uat:
    runs-on: ubuntu-latest
    if: startsWith(github.ref_name, 'hotfix-prod') == false && failure() != true && cancelled() != true
    environment: uat
    needs: [qa,dev]
    steps:
      - name: Print Environment
        run: echo "Deploying to uat"

  preprod:
    runs-on: ubuntu-latest
    if: failure() != true && cancelled() != true
    needs: [uat]
    environment: preprod
    steps:
      - name: Print Environment
        run: echo "Deploying to preprod"

  prod:
    runs-on: ubuntu-latest
    if: failure() != true && cancelled() != true
    needs: [preprod]
    environment: prod
    steps:
      - name: Print Environment
        run: echo "Deploying to prod"
